libmbp/patcherconfig.cpp

Signed-off-by: zeeshan <zeeshanhussain12@gmail.com>
@chenxiaolong  the previous one had some derps. 
multiboot is working great. heavily tested. 
Confirmed working :dancer:

libmbp: patcherconfig.cpp: Add support for condor

---

libmbp/devices/lg.cpp

Add support LG L7 First Gen and Second Gen

libmbp: Add support for LG L7 Brothers

---

libmbp/devices/paths.h
libmbp/devices/samsung.cpp

It's almost same with exynos5433 devices.
Logs :
https://drive.google.com/file/d/0B70olIYdy7cYUTZRLTFyUTBKVXM/view?usp=sharing

libmbp: Add support for slte

---

libmbp/devices/motorola.cpp

Please review and add if you can.

Adding all the surnia CDMA variants (Moto E 2015)

---

libmbp/CMakeLists.txt
libmbp/devices/google.cpp
libmbp/devices/google.h
libmbp/patcherconfig.cpp

Signed-off-by: Anik khan <anik9280@gmail.com>

DualBootPatcher: Add Android One Devices

---

.gitmodules
cmake/Dependencies.cmake
cmake/dependencies/liblzma.cmake
cmake/dependencies/lz4.cmake
cmake/dependencies/lzo.cmake
cmake/dependencies/zlib.cmake

It's not our job to provide every single dependency we use. We should provide only the forked dependencies. The others are up to the user to obtain.

Remove submodules for non-fork dependencies

---

libmbp/devices/samsung.cpp

Signed-off-by: corphish <d97.avinaba@gmail.com>

Add support for Samsung mint2g

---

libmbp/devices/samsung.cpp

Signed-off-by: celoxs2 garry.windows8@gmail.com

Add support for Galaxy S5 "kltekdi"

---

libmbp/devices/samsung.cpp

Heres 3 devices tested and working , ( Im The Mr im providing a custom version of dual boot patcher ofc giving credits too :P i will continue the custom version as well )
only lte Exynos version of s5 mini is not tested

Added 3 devices all variants

---

libmbp/devices/pantech.cpp

Add support for Pantech Vega Iron 
Initial attempt at VEGA IRON 2 Boot UI support

Add support for Pantech Vega Iron && Initial attempt at VEGA IRON 2 Boot UI support

---

libmbp/devices/motorola.cpp

There's some devices that are identified as surnia_umts and it's the same device (surnia) so, it's just a matter to make it compatible

Adding surnia_umts

---

libmbp/devices/pantech.cpp

libmbp: Fix correct name of Pantech device 			
libmbp: Reinitial attempt at VEGA IRON & VEGA IRON2 Boot UI support

libmbp: Update for Pantech device

---

Android_GUI/res/values-ru-rRU/strings.xml
Android_GUI/res/values-ru/strings.xml
libmbp/CMakeLists.txt
libmbp/devices/samsung.cpp
libmbp/devices/theo.cpp
libmbp/devices/theo.h
libmbp/src/patcherconfig.cpp
mbbootui/theme/common/languages/ru.xml

Added full Russian translation for Android_GUI and add Boot UI language file

Add full Russian translation; Galaxy Note 3 Boot UI and other devices support.

---

mbtool/installer.cpp

This eliminates the need to switch to the desired ROM prior to flashing
a zip that modifies the existing boot partition contents.

mbtool: installer.cpp: Switch to target ROM before flashing (fixes #93)

---

data/devices/oneplus.yml

BootUI support for Oneplus One

Add BootUI for Oneplus One

---

mbtool/CMakeLists.txt
mbtool/auditd.cpp
mbtool/auditd.h
mbtool/external/audit/libaudit.cpp
mbtool/external/audit/libaudit.h
mbtool/main.cpp

This will help with SELinux debugging, especially for adding support for TouchWiz 6.0 ROMs.

mbtool: Add simple kernel audit message logger tool

---

data/devices/lenovo.yml

Should fix the random and annoying detection errors on stock

Split P1a4x into P1a41 and P1a42

---

mbtool/appsync.cpp
mbtool/init.cpp

This fixes boot issues since appsync no longer runs when it is disabled.

mbtool: Move /data/.layout_version creation to init.cpp

---

Android_GUI/res/values-ru-rRU/strings.xml
Android_GUI/res/values-ru/strings.xml
mbbootui/theme/common/languages/ru.xml

Added strings about backup and restore in app.
Added strings about timeout, skip timeout in Boot UI.
Updated sring about chosing ROMs in Boot UI.

Update RU strings

---

data/devices/samsung/01_galaxy_note.yml

Update 01_galaxy_note.yml for for Galaxy Note Edge / tblte

Add support for Galaxy Note Edge / tblte

---

data/devices/xiaomi.yml

it's quite challenging to setting up the environment
but at the end of the compiling, i got an error such as
cmake version is an old one , or we need an extra library
hope you can compile it, and i will test it 
thanks before 
*i made it on top of staging, since i saw there is a lots of changes with xiaomi.yml :)

Add support for ferrari

---

data/devices/CMakeLists.txt
data/devices/yu.yml

Could you please do a test build? I couldn't build it myself.

data: Add support for lettuce

---

data/devices/xiaomi.yml

Add configuration for XiaoMi Redmi 4 prime ((markw))

Add XiaoMi Redmi 4 (markw) device

---

data/devices/yu.yml

Commit's by Anand Shekhawat, I'm just giving the PR.

data: Add support for tomato

---

data/devices/motorola.yml

UI itself confirmed working on my device.
However WiFi doesn't seem to work correctly (not connecting at boot, manual connect works), any idea?

Enable boot UI for victara

---

data/devices/xiaomi.yml

mi5s plus support.
Add bootUI plz

Mi5s Plus (natrium) support

---

data/devices/huawei.yml

Add support to Huawei Y6

---

data/devices/huawei.yml

Update codename and block info.

update device info for Huawei Y6

---

data/devices/CMakeLists.txt
data/devices/coolpad.yml

Please add support coolpad note 3 , note 3 lite and note 3 plus.
I have tested this patch by edoting devices.json file everything working fine.
only backup rom is not working

Add support to coolpad

---

data/devices/samsung/02_galaxy_a_j.yml

Add samsung j5 support

---

data/devices/google.yml

Hi support n7100 T03g.    if it needs further information on the device I write how to take them. thank you

Add support for n7100 t03g international

---

data/devices/oneplus.yml

The 3T uses identical partition Layout to the 3, so copied, confirmed same, edited names.

Added Oneplus 3T Support

---

data/devices/xiaomi.yml

I think that all normal now. I fixed previous bug ( if it can be called a bug ).

Add Xiaomi Mi 5S (capricorn)

---

data/devices/elephone.yml

fix a typo for elephone p8000

---

data/devices/lenovo.yml

Please add support for Lenovo ZUK Z2

---

data/devices/samsung/07_other.yml

@chenxiaolong Can you merge this PR?

Add support for Samsung Galaxy Trend Plus/Samsung Galaxy S Duos 2 (kylepro/kyleprods)

---

Android_GUI/res/values-zh-rCN/strings.xml

Add Chinese language

---

data/devices/xiaomi.yml

Support for Xiaomi Redmi Note 4 (mido)

Support for Xiaomi Redmi Note 4 (mido)

---

data/devices/lenovo.yml

Hi Chen, please add support for Lenovo Vibe P2.

Add support for Lenovo Vibe P2

---

data/devices/samsung/03_galaxy_ace.yml

Add Support for Samsung Galaxy Ace 4 Neo Duos (SM-G318ML)

Add support for Samsung Galaxy Ace 4 Neo

---

data/devices/lenovo.yml

Plz verify the patch for k4 note support and merge it sir plz and make a snapshot version out of it asap so i can dual boot

Unified DBP for 2gb and 3gb Variant of Lenovo k4 and minor mistakes Improved Plz add support 😃😃😃😃

---

data/devices/xiaomi.yml

Add Kate like Kenzo (only rom change not device blocks)

Add Support for Xiaomi Redmi Note 3 SE (Kate)

---

data/devices/huawei.yml

I added Huawei Honor 8 for DualBootPatcher. 
Hope you will update it! :smile: 
Also, my gmail is "handwerstudotie@gmail.com".

Add support for Huawei Honor 8

---

data/devices/huawei.yml

add supports for Huawei P9 Plus

Add Huawei P9 Plus

---

data/devices/lenovo.yml

Add additional codenames for Lenovo Vibe P2

---

odinupdater/odinupdater.cpp

odinupdater: Allow flashing without CSC

---

mbtool/installer.cpp

mbtool: installer.cpp: Log details if boot image flashing fails

---

data/devices/asus.yml

Additional partitiom detailes for ze550kl

---

data/devices/huawei.yml

adding huawei-Y636 device spesifications

Update huawei.yml for huawei Y635 support

---

data/devices/CMakeLists.txt
data/devices/cherrymobile.yml

Added Support For Cherry Mobile Flare S5

Support For Cherry Mobile Flare S5

---

data/devices/meizu.yml

Add support for M/N partition table

devices: meizu: Add more ways to partitions

---

data/devices/asus.yml

- add zenfone Selfie support

---

data/devices/samsung/01_galaxy_note.yml

Add support for  n9200 samsung

---

data/devices/xiaomi.yml

http://pastebin.com/vBbcsG6V
Signed-off-by: Deepak Sharma <TechExhibeo@gmail.com>

devices: hydrogen: Add Marshmallow block device paths

---

docs/BUILD-Utilities.md

docs: Add documentation on building the utilities zip (fixes #590)

---

Android_GUI/build.gradle.in

Android GUI: Update gradle plugin to 2.3.3

---

libmbpio/src/directory.cpp

The Win32 API does not return `ERROR_ALREADY_EXISTS` when calling `CreateDirectoryW(L"c:\\", nullptr)`.
This reverts commit c54a32dccc90f4dbdcac2126e820abe45b3704d1.

Revert "libmbpio: Remove unnecessary existence check in createDirectories() for Win32"

---

data/devices/xiaomi.yml

- Added: 
Xiaomi Mi 6
Xiaomi Redmi 4A
- Enable Bootui:
Xiaomi Mi Max
Xiaomi Mi Max Pro

Add MI 6 & Redmi 4A

---

data/devices/meizu.yml

Add support for Meizu Pro 5

---

data/devices/asus.yml

Add support for
- ZenFone 3 Deluxe (ZS570KL)
- ZenFone 3 (ZE552KL)
- ZenFone 3 (ZE520KL)

Add more ASUS devices

---

Android_GUI/src/com/github/chenxiaolong/dualbootpatcher/nativelib/LibMbDevice.java

Android GUI: LibMbDevice: Can't instantiate non-static inner class SizeT

---

data/devices/samsung/01_galaxy_note.yml

data: 01_galaxy_note.yml: Fix invalid indentation

---

data/devices/xiaomi.yml

Please add device Xiaomi Redmi Note 4G.

Add device Xiaomi Redmi Note 4G

---

data/devices/walton.yml

Add Walton Primo N2 MT6580 device

Aded Walton Primo N2

---

.tx/config
Android_GUI/res/values-id-rID/strings.xml
Android_GUI/res/values-pl-rPL/strings.xml
Android_GUI/res/values-vi/strings.xml
Android_GUI/res/values-zh-rCN/strings.xml
Android_GUI/res/values-zh-rTW/strings.xml
Android_GUI/res/values-zh/strings.xml

Android GUI: Update translations from Transifex

---

data/devices/sony.yml

Add Sony Xperia M support

---

data/devices/CMakeLists.txt
data/devices/alcatel.yml

Add Alcatel Pixi 4-4 support

---

data/devices/CMakeLists.txt
data/devices/doogee.yml

Add support for Doogee devices

---

data/devices/CMakeLists.txt
data/devices/gionee.yml

- GiONEE P5W
- GiONEE Marathon Mini
MT6580 devices

Add support for Gionee devices

---

data/devices/CMakeLists.txt
data/devices/leagoo.yml

Add Leagoo Z5 support

---

data/devices/CMakeLists.txt
data/devices/symphony.yml

Add Symphony P7 support

---

data/devices/CMakeLists.txt
data/devices/cagabi.yml

It is a MT6580 device running Android 6.0

Add Cagabi One suppport

---

data/devices/asus.yml

support asus zenfone max

---

libmbutil/src/archive.cpp
libmbutil/src/chmod.cpp
libmbutil/src/chown.cpp
libmbutil/src/copy.cpp
libmbutil/src/delete.cpp
libmbutil/src/fstab.cpp
libmbutil/src/fts.cpp
libmbutil/src/loopdev.cpp
libmbutil/src/mount.cpp
libmbutil/src/path.cpp
mbtool/appsync.cpp
mbtool/daemon_v3.cpp
mbtool/init.cpp
mbtool/installer.cpp
mbtool/installer.h
mbtool/installer_util.cpp
mbtool/miniadbd.cpp
mbtool/mount_fstab.cpp
mbtool/mount_fstab.h
mbtool/multiboot.cpp
mbtool/properties.cpp
mbtool/ramdisk_patcher.cpp
mbtool/rom_installer.cpp
mbtool/roms.cpp
mbtool/signature.cpp
mbtool/switcher.cpp
mbtool/utilities.cpp
mbtool/wipe.cpp

libmbutil,mbtool: Remove unneeded namespace qualifiers

---

devicesgen/devicesgen.cpp

See for more details:
https://github.com/jbeder/yaml-cpp/issues/261#issuecomment-223191708

devicesgen: Treat quoted YAML values as strings

---

data/devices/motorola.yml

Add support for Motorola Moto G5 Plus - XT1687 / potter.

Add support for Motorola Moto G5 Plus

---

examples/CMakeLists.txt
examples/bootimg_compare.cpp

examples: Add tool to compare two boot images

---

data/devices/lenovo.yml

ZUK Z1: enable boot UI

---

libmbcommon/include/mbcommon/finally.h
mbbootui/daemon_connection.cpp
mbtool/installer.cpp

libmbcommon: Make Finally dismissible and movable

---

docker/common.sh
docker/template/Dockerfile.base.in
docs/DOCKER.md

docker: Update base image to fedora:26

---

docker/common.sh
docker/template/Dockerfile.mingw.in
docs/DOCKER.md

docker: Add p7zip-plugins to mingw image

---

data/devices/wileyfox.yml

Added parameters for Wileyfox Swift2 (Swift2Plus/Swift2X) devices.

Add support for Wileyfox Swift2

---

data/devices/htc.yml

Well, I found the block of pmewl is same with the block of pmewhl.

Add htc_pmewl

---

data/devices/walton.yml

Add new model support for Walton Primo RX5

Add support for Primo RX5

---

cmake/CompilerFlags.cmake
libmbcommon/include/mbcommon/flags.h
libmbcommon/include/mbcommon/integer.h
libmbdevice/include/mbdevice/flags.h
libmbdevice/src/capi/device.cpp
libmbdevice/src/capi/json.cpp
libmbdevice/tests/test_flags.cpp
libmbdevice/tests/test_json.cpp
libmblog/src/logging.cpp
libmbpio/src/win32/delete.cpp
libmbutil/include/mbutil/properties.h
mbbootui/daemon_connection.cpp

cmake: Target C++14

---

CMakeLists.txt
android/CMakeLists.txt
bootimgtool/CMakeLists.txt
cmake/CompilerFlags.cmake
cmake/libc++-hack/CMakeLists.txt
cmake/libc++-hack/src/lib.cpp
libmbbootimg/src/format/android_error.cpp
libmbbootimg/src/format/loki_error.cpp
libmbbootimg/src/format/mtk_error.cpp
libmbbootimg/src/format/segment_error.cpp
libmbbootimg/src/format/sony_elf_error.cpp
libmbbootimg/src/reader_error.cpp
libmbbootimg/src/writer_error.cpp
libmbcommon/src/file_error.cpp
libmbcommon/src/file_util.cpp
libmbdevice/include/mbdevice/device.h
libmbdevice/src/json.cpp
libmbutil/src/external/system_properties.cpp
libmbutil/src/string.cpp
mbbootui/CMakeLists.txt
mbtool/CMakeLists.txt
mbtool/appsync.cpp
mbtool/daemon.cpp
mbtool/daemon_v3.cpp
mbtool/external/property_service.cpp
mbtool/installer.cpp
mbtool/rom_installer.cpp
mbtool/romconfig.cpp
mbtool/update_binary.cpp
odinupdater/CMakeLists.txt

cmake: Switch to libc++ on Android for better C++14 support

---

docker/template/Dockerfile.android.in
docker/template/Dockerfile.base.in

Upstream bug report: https://bugzilla.redhat.com/show_bug.cgi?id=1483553

docker: Switch to registry.fedoraproject.org/fedora:26 image to work around RHBZ#1483553

---

data/devices/pantech.yml

add support for IM-A890, add codename for old devices

---

libmbcommon/CMakeLists.txt
libmbcommon/include/mbcommon/common.h
libmbcommon/src/common.cpp

libmbcommon: Add macros for handling unreachable code

---

libmbdevice/include/mbdevice/device.h
libmbdevice/include/mbdevice/device_p.h
libmbdevice/src/device.cpp

libmbdevice: Remove use of pimpl

---

libmbbootimg/include/mbbootimg/format/segment_error_p.h
libmbbootimg/include/mbbootimg/format/segment_reader_p.h
libmbbootimg/include/mbbootimg/format/segment_writer_p.h
libmbbootimg/src/format/android_reader.cpp
libmbbootimg/src/format/android_writer.cpp
libmbbootimg/src/format/loki_reader.cpp
libmbbootimg/src/format/loki_writer.cpp
libmbbootimg/src/format/mtk_reader.cpp
libmbbootimg/src/format/mtk_writer.cpp
libmbbootimg/src/format/segment_error.cpp
libmbbootimg/src/format/segment_reader.cpp
libmbbootimg/src/format/segment_writer.cpp
libmbbootimg/src/format/sony_elf_reader.cpp
libmbbootimg/src/format/sony_elf_writer.cpp

libmbbootimg: segment: Remove segment count limit and improve API

---

bootimgtool/bootimgtool.cpp

bootimgtool: Add help text for --input-aboot

---

data/devices/lg.yml

Requesting to have the LG Stylo 3 Plus to be added.  Sf340n .  Similiar to the stylo 2.

Add support for LG Stylo 3 Plus

---

data/devices/micromax.yml

Added Support For Micromax Unite 2 A106 - MT6582 ...

Added Support For Micromax Unite 2 A106 (MTK)

---

data/devices/CMakeLists.txt
data/devices/zoji.yml

Hi. Please add homtom zoji z7. Thank You.

Add HOMTOM ZOJI Z7

---

data/devices/xiaomi/03_redmi.yml

Add support for Xiaomi Note Pro

---

data/devices/meizu.yml

Updated one file, which is the 'date/devices/meizu.yml'.

Add Support For Meizu M3 Note

---

Android_GUI/src/com/github/chenxiaolong/dualbootpatcher/freespace/FreeSpaceFragment.java

Android GUI: Ignore tracefs filesystems on Free Space page

---

data/devices/oppo.yml

Add codename "F1f" as it came up with an installation error on some of the devices

Add codename "F1f" and some extra partitions

---

libmbbootimg/src/format/loki.cpp
libmbbootimg/tests/format/test_android_reader.cpp
libmbcommon/src/file/memory.cpp
libmbcommon/tests/test_file_util.cpp
libmbpatcher/src/patchers/odinpatcher.cpp
libmbsign/src/mbsign.cpp
libmbsparse/src/sparse.cpp
libmbutil/src/archive.cpp
libmbutil/src/loopdev.cpp
libmbutil/src/selinux.cpp
libmbutil/src/string.cpp
mbbootui/daemon_connection.cpp
mbtool/appsync.cpp
mbtool/daemon.cpp
odinupdater/fuse-sparse.cpp

*: Avoid memset where possible

---

Android_GUI/build.gradle.in

Android GUI: Update Architecture Components to 1.1.0

---

Android_GUI/build.gradle.in
Android_GUI/src/com/github/chenxiaolong/dualbootpatcher/NullOutputStream.kt
Android_GUI/src/com/github/chenxiaolong/dualbootpatcher/RomConfig.kt
Android_GUI/src/com/github/chenxiaolong/dualbootpatcher/RomUtils.kt
Android_GUI/src/com/github/chenxiaolong/dualbootpatcher/appsharing/AppListFragment.kt
Android_GUI/src/com/github/chenxiaolong/dualbootpatcher/appsharing/AppSharingService.kt
Android_GUI/src/com/github/chenxiaolong/dualbootpatcher/appsharing/AppSharingSettingsFragment.kt
Android_GUI/src/com/github/chenxiaolong/dualbootpatcher/nativelib/LibMiniZip.kt
Android_GUI/src/com/github/chenxiaolong/dualbootpatcher/patcher/PatchFileFragment.kt
Android_GUI/src/com/github/chenxiaolong/dualbootpatcher/patcher/PatcherService.kt
Android_GUI/src/com/github/chenxiaolong/dualbootpatcher/patcher/PatcherUtils.kt
Android_GUI/src/com/github/chenxiaolong/dualbootpatcher/pathchooser/PathChooserDialog.kt
Android_GUI/src/com/github/chenxiaolong/dualbootpatcher/socket/MbtoolConnection.kt
Android_GUI/src/com/github/chenxiaolong/dualbootpatcher/switcher/MbtoolTaskOutputFragment.kt
Android_GUI/src/com/github/chenxiaolong/dualbootpatcher/switcher/service/CreateRamdiskUpdaterTask.kt
Android_GUI/src/com/github/chenxiaolong/dualbootpatcher/switcher/service/MbtoolTask.kt

Its latest version depends on Java features not available on Android and
the Kotlin standard library natively supports the features we need
anyway.

Android GUI: Remove Apache commons-io dependency

---

Android_GUI/build.gradle.in
Android_GUI/src/com/github/chenxiaolong/dualbootpatcher/FileUtils.kt
Android_GUI/src/com/github/chenxiaolong/dualbootpatcher/MainActivity.kt
Android_GUI/src/com/github/chenxiaolong/dualbootpatcher/switcher/service/MbtoolTask.kt

Android GUI: Replace commons-lang3 with commons-text

---

data/devices/xiaomi/03_redmi.yml

 Add new device : Xiaomi Redmi 5 Plus

---

Android_GUI/src/com/github/chenxiaolong/dualbootpatcher/CommandUtils.kt
Android_GUI/src/com/github/chenxiaolong/dualbootpatcher/LogUtils.kt
Android_GUI/src/com/github/chenxiaolong/dualbootpatcher/patcher/PatcherService.kt
Android_GUI/src/com/github/chenxiaolong/dualbootpatcher/switcher/SwitcherService.kt

Android GUI: CommandUtils: Fix synchronization on incorrect variable when using lock

---

data/devices/xiaomi/03_redmi.yml

Sorry for the mistake.
Everything works well now.

Fix a bug for xiaomi redmi 5 plus

---

mbtool/utilities.cpp

mbtool: utilities: Fix base stream and _handle not being set

---

Android_GUI/src/com/github/chenxiaolong/dualbootpatcher/switcher/service/MbtoolTask.kt

Android GUI: Dump logcat after mbtool tasks execute

---

libmblog/src/logging.cpp

libmblog: Shorten log level text

---

libmbutil/include/mbutil/path.h
libmbutil/include/mbutil/time.h
libmbutil/src/path.cpp
libmbutil/src/time.cpp
mbbootui/gui/blanktimer.cpp
mbbootui/gui/blanktimer.hpp
mbbootui/gui/gui.cpp
mbbootui/twrp-functions.cpp
mbtool/appsync.cpp
mbtool/backup.cpp
mbtool/emergency.cpp
mbtool/installer.cpp
mbtool/mount_fstab.cpp

libmbutil: Replace time functions with std::chrono where possible

---

libmbdevice/src/json.cpp

libmbdevice: Fix unnecessary calls to Document::GetAllocator()

---

mbtool/init.cpp

mbtool: Fix hanging boot when app sharing is disabled

---

mbtool/sepolpatch.cpp

mbtool: Allow mbtool connections from any SELinux context beginning with "untrusted_app_"

---

libmbpatcher/include/mbpatcher/patchers/odinpatcher.h
libmbpatcher/src/patchers/odinpatcher.cpp
odinupdater/odinupdater.cpp

This is just the first step to getting a TouchWiz Oreo ROM patched and flashed. The resulting installation is not bootable yet.

Initial support for patching/flashing non-Treble TouchWiz Oreo ROMs

---

odinupdater/odinupdater.cpp

Normally, DualBootPatcher avoids touching the ROM in any way unless it's
absolutely necessary. In this case, removing RLC is warranted since the
bootloader will get relocked for 7 days if it's present after a reboot.

odinupdater: Remove RLC and disable vaultkeeper during installation

---

docs/internals/Odin-Package-Installation.md

docs: Document RLC removal process

---

CMakeLists.txt
README.md

CMakeLists.txt: We actually rely on CMake 3.8 features

---

mbtool/init.cpp

mbtool: init.cpp: Remove unused variables and functions

---

cmake/dependencies/googletest.cmake

external: Update googletest to latest master

---

cmake/dependencies/minizip.cmake
libmbpatcher/CMakeLists.txt
mbtool/CMakeLists.txt

external: Update minizip to latest master (v2.3.1)

---

mbtool/packages.cpp
mbtool/packages.h

mbtool: packages.cpp: Update private flags for Oreo

---

mbtool/initwrapper/devices.cpp

mbtool: Replace pthread with std::thread

---

libmbutil/external.yaml
libmbutil/include/mbutil/external/_system_properties.h
libmbutil/include/mbutil/external/system_properties.h
libmbutil/src/external/system_properties.cpp

libmbutils: Rebase properties implementation on bionic android-8.1.0_r29

---

Android_GUI/res/values/strings.xml
Android_GUI/src/com/github/chenxiaolong/dualbootpatcher/switcher/SwitcherService.kt

Android GUI: SwitcherService.kt: Use notification channels on Android 8.0+

---

mbbootui/daemon_connection.cpp
mbtool/appsync.cpp
mbtool/daemon.cpp
mbtool/src/util/uevent_thread.cpp

mbtool,mbbootui: Set cloexec for sockets where possible

---

mbtool/installer.cpp
mbtool/switcher.cpp
mbtool/switcher.h

mbtool: switcher: Small refactor of checksum properties file code

---

libmbutil/include/mbutil/command.h
libmbutil/src/command.cpp
libmbutil/src/reboot.cpp
mbtool/appsync.cpp
mbtool/daemon_v3.cpp
mbtool/image.cpp
mbtool/init.cpp
mbtool/installer.cpp
mbtool/installer.h
mbtool/mount_fstab.cpp
mbtool/rom_installer.cpp
mbtool/update_binary.cpp
odinupdater/odinupdater.cpp

libmbutil: command.cpp: Refactor API to use std::function and std::string_view

---

mbtool/mount_fstab.cpp

mbtool: mount_fstab.cpp: Actually parse VFS options when bind mounting as read-only

---

Android_GUI/CMakeLists.txt
Android_GUI/build.gradle.in
Android_GUI/res/values/strings.xml
Android_GUI/src/com/github/chenxiaolong/dualbootpatcher/AboutFragment.kt

Android GUI: Link to exact commit for source code and license URLs

---

libmbpatcher/include/mbpatcher/private/fileutils.h
libmbpatcher/include/mbpatcher/private/miniziputils.h
libmbpatcher/src/patchers/odinpatcher.cpp
libmbpatcher/src/patchers/ramdiskupdater.cpp
libmbpatcher/src/patchers/zippatcher.cpp
libmbpatcher/src/private/fileutils.cpp
libmbpatcher/src/private/miniziputils.cpp
mbtool/utilities.cpp

Fix incorrect add_file() overload being called

---

data/devices/sony.yml

add device Sony Xperia Z5 Premium supported

---

mbtool/installer_util.cpp

mbtool: installer_util.cpp: Switch cwd instead of hardcoding temp dir

---

data/devices/cherrymobile.yml

Add RGxS5 to Cherry Mobile Flare S5 codenames

---

data/devices/huawei.yml

Fixed wrong codenames

---

data/devices/samsung/02_galaxy_a_j.yml

Added j5 2016 support

---

data/devices/micromax.yml

Micromax A310 & A311 support added

Added support for Micromax Canvas Nitro devices

---

Android_GUI/res/values-ru/strings.xml
data/devices/meizu.yml

for devices with unlocked bootloades only

add meizu M6 Note Support

---

data/devices/CMakeLists.txt
data/devices/homtom.yml

I would like to add support for the Homtom HT10

Add the Homtom HT10 to the list of supported devices

---

data/devices/huawei.yml

huawei.yml: Fix syntax error that does fail with yaml-cpp

---

cmake/CompilerFlags.cmake
libmbsign/include/mbsign/error.h
libmbutil/include/mbutil/fstab.h

external: Update outcome to latest commit

---

data/devices/nextbit.yml

Added a needed flag as well as the cpu temp path.

Fix boot UI configuration for Nextbit Robin

---

libmbcommon/include/mbcommon/locale.h
libmbcommon/src/locale.cpp
libmbcommon/tests/test_locale.cpp

libmbcommon: Use std::basic_string_view<> for locale API

---

libmiscstuff-jni/libmiscstuff.cpp

libmiscstuff: Fix memory leak if throwing Java exception via JNI fails

---

libmblog/src/logging.cpp

libmblog: Shorten tag by default

---

docker/common.sh
docker/template/Dockerfile.base.in
docker/template/Dockerfile.mingw.in
docs/build/Docker.md

docker: Rebase images on Fedora 29

---

libmbbootimg/src/format/android_reader.cpp
libmbbootimg/src/format/android_writer.cpp
libmbbootimg/src/format/loki.cpp
libmbbootimg/src/format/loki_reader.cpp
libmbbootimg/src/format/loki_writer.cpp
libmbbootimg/src/format/mtk_reader.cpp
libmbbootimg/src/format/mtk_writer.cpp
libmbbootimg/src/format/segment_reader.cpp
libmbbootimg/src/format/segment_writer.cpp
libmbbootimg/src/format/sony_elf_reader.cpp
libmbbootimg/src/format/sony_elf_writer.cpp
libmbbootimg/src/reader.cpp
libmbcommon/include/mbcommon/file.h
libmbcommon/include/mbcommon/file_p.h
libmbcommon/src/file.cpp
libmbcommon/src/file/callbacks.cpp
libmbcommon/src/file_util.cpp
libmbcommon/tests/test_file.cpp
libmbsparse/src/sparse.cpp
libmbsparse/tests/test_sparse.cpp

libmbcommon: Remove concept of fatal state from mb::File

---

libmbbootimg/include/mbbootimg/reader.h
libmbbootimg/include/mbbootimg/reader_p.h
libmbbootimg/include/mbbootimg/writer.h
libmbbootimg/include/mbbootimg/writer_p.h
libmbbootimg/src/format/android_writer.cpp
libmbbootimg/src/format/loki.cpp
libmbbootimg/src/format/loki_writer.cpp
libmbbootimg/src/format/mtk_writer.cpp
libmbbootimg/src/format/segment_reader.cpp
libmbbootimg/src/format/segment_writer.cpp
libmbbootimg/src/format/sony_elf_writer.cpp
libmbbootimg/src/reader.cpp
libmbbootimg/src/writer.cpp

libmbbootimg: Remove concept of fatal state

---

libmbcommon/src/file_util.cpp

libmbcommon: file_util.cpp: Simplify file_move function

---

cmake/Qemu.cmake

cmake: Hide kernel output for qemu-tests target

---

mbtool/src/recovery/installer.cpp

mbtool: installer.cpp: Account for TWRP's /dev/__properties_kk__

---

.tx/config

.tx: Update location to translation files

---

mbtool/include/recovery/installer.h
mbtool/include/util/multiboot.h
mbtool/src/recovery/installer.cpp

mbtool: Add support for Android 4.4-6.0 file-based /dev/__properties__

---

Android_GUI/src/main/java/com/github/chenxiaolong/dualbootpatcher/switcher/InAppFlashingFragment.kt

Android GUI: Fix crash during orientation change in InAppFlashingFragment

---

Android_GUI/build.gradle.in
Android_GUI/src/main/java/com/github/chenxiaolong/dualbootpatcher/MainActivity.kt
Android_GUI/src/main/java/com/github/chenxiaolong/dualbootpatcher/appsharing/AppListFragment.kt
Android_GUI/src/main/java/com/github/chenxiaolong/dualbootpatcher/appsharing/AppSharingSettingsActivity.kt
Android_GUI/src/main/java/com/github/chenxiaolong/dualbootpatcher/patcher/AutomatedPatcherActivity.kt
Android_GUI/src/main/java/com/github/chenxiaolong/dualbootpatcher/pathchooser/PathChooserActivity.kt
Android_GUI/src/main/java/com/github/chenxiaolong/dualbootpatcher/settings/RomSettingsActivity.kt
Android_GUI/src/main/java/com/github/chenxiaolong/dualbootpatcher/settings/RomSettingsFragment.kt
Android_GUI/src/main/java/com/github/chenxiaolong/dualbootpatcher/switcher/AutomatedSwitcherActivity.kt
Android_GUI/src/main/java/com/github/chenxiaolong/dualbootpatcher/switcher/InAppFlashingFragment.kt
Android_GUI/src/main/java/com/github/chenxiaolong/dualbootpatcher/switcher/MbtoolTaskOutputActivity.kt

Android GUI: Update kotlin to 1.3.20 and use Android KTX libraries

---

libmbutil/src/reboot.cpp

libmbutil: Remount block devices as read-only if unmounting fails during reboot

---

README.md
thirdparty/CMakeLists.txt
thirdparty/android-system-core/PKGBUILD
thirdparty/freetype2/PKGBUILD
thirdparty/libarchive/PKGBUILD

DualBootPatcher is no longer in development
