libmbp/patcherconfig.cpp
MultiBoot support for the Huawei Ascend Mate 2 device.
* Heavily tested and confirmed working.
* Roms tested and verified:
** Stock 5.1 EMUI Lollipop
** Cyanogenmod 12.1
** Cyanogenmod 13.0
** Carbon Rom 5.1.1
** Pac Rom 5.1.1
=> libmbp: patcherconfig.cpp: Add support for mt2l03

libmbp/devices/samsung.cpp
jactivelteskt has many diffrent from jflte. (Same S4 Active, but has diffrent AP)
So it need to create new device list.
=> libmbp: Add support for jactivelteskt

data/scripts/bb-wrapper.sh, libmbutil/src/loopdev.cpp, mbtool/installer.cpp
It's ridiculous that these hacks are necessary, but what can I do about it?
=> Workaround installation issues of systemless SuperSU due to its hardcoded /dev/block/loop0 path

libmbp/devices/motorola.cpp
"ls -l /dev/block/platform/msm_sdcc.1/by-name/
system -> /dev/block/mmcblk0p38
cache -> /dev/block/mmcblk0p37
userdata -> /dev/block/mmcblk0p39
boot -> /dev/block/mmcblk0p33
recovery -> /dev/block/mmcblk0p34"
ps: The unique differences of the 2013 version is /cache and /userdata partition (maybe /recovery too)
ps2: Fixed mistype on Moto X 2013
ps3: Not tested, due to fault on my PC
ps4: Made with help @lucasdessy
Signed-off-by: Caio Oliveira <caiooliveirafarias0@gmail.com>
=> libmbp: Support Moto X 2014

libmbp/devices/asus.cpp
we can still use the same setId i.e. Z00A since we only need the correct code name.
Signed-off-by: sayeed99 <sayeed.afridi2009@gmail.com>
=> Add Asus Zenfone 2 [Z008] aka ZE550ML

libmbp/devices/samsung.cpp
The Wifi versions of Galaxy TabS2 are there but no LTE Version
=> Add LTE Versions of the Galaxy TabS2

libmbp/devices/lg.cpp
I made a tiny addition to support for LG G2 Korean model.
and I confirm that it works correctly.
This is the partition information of 'f320' which is the device name of LG G2 Korean variant.
http://pastebin.com/N4J1Dsfk
Thank you
=> Add codename for LG G2 Korean variant

mbtool/CMakeLists.txt, mbtool/file_contexts.cpp, mbtool/file_contexts.h, mbtool/init.cpp, mbtool/main.cpp, mbtool/multiboot.h
This fixes the patching of `/file_contexts.bin` on Android 7.0.
=> mbtool: Convert binary /file_contexts.bin file to text-based file

odinupdater/odinupdater.cpp
This prevents `odinupdater` from failing now that `update-binary-tool` handles all the mounting instead of just returning 0.
=> mbtool: Check if /system is mounted before attempting to unmount it

libmbutil/src/external/system_properties.cpp
This can't be done before SELinux is initialized, which is the case in
the mbtool boot environment.
=> mbutil: external: Don't set property file SELinux label

mbbootui/daemon_connection.cpp
When getting the list of installed ROMs from the daemon, the client did
not check if the fields (system path, build, version, etc.) were NULL
before accessing them. This would cause the Boot UI to crash upon
selection of the Switch ROM page. Under normal operation, this could
happen if, for any ROM:
* The build.prop file is not found or not readable
* The build.prop file is missing properties for the build and version
* The ROM uses a system image and thus, the build.prop file cannot be
read
=> mbbootui: Fix null pointer dereferencing if daemon returns incomplete ROM data

libmbp/include/mbp/autopatchers/standardpatcher.h, libmbp/src/autopatchers/standardpatcher.cpp
CM 13 and earlier contained an updater-script file that did not verify
the result of block_image_update(). If a BLKDISCARD ioctl call failed
before, it would simply be ignored. This changed with CM 14, which
properly checks the return value of block_image_update(). We'll work
around the issue by removing the 'erase' command in
system.transfer.list.
=> libmbp: Strip 'erase' command in system.transfer.list due to BLKDISCARD bugs on some devices

mbtool/init.cpp
Some kernels don't respect
klogctl(KLOG_CONSOLE_LEVEL, nullptr, 7)
so valuable log messages are lost when looking at /proc/last_kmsg or
/sys/fs/pstore/console-ramoops. We'll work around this by logging
everything as errors.
=> mbtool: Force kmsg error levels to all be errors

mbtool/mount_fstab.cpp
Nougat ROMs no longer use the /cache partition (if one exists) and
instead symlink /cache to /data/cache.
=> mbtool: Skip mounting ROM-specific /cache if /cache is a symlink

mbtool/mount_fstab.cpp
check_nnp_nosuid() in security/selinux/hooks.c of the kernel source code
calls security_bounded_transition() for mount points with the nosuid
flag set. This will cause the process of setexeccon'ing to
fsck_untrusted and exec'ing a 'fsck_exec' labeled binary to fail unless
an appropriate typebounds statement exists in the policy.
Sample audit message for failure:
```
type=1401 audit(1478575822.166:457): op=security_bounded_transition seresult=denied oldcontext=u:r:vold:s0 newcontext=u:r:fsck_untrusted:s0
```
We fix this by simply not mounting the /wrapped mount point with nosuid,
which matches the mount options for /system anyway.
=> mbtool: Don't mount wrapped binaries image with MS_NOSUID

Android_GUI/src/com/github/chenxiaolong/dualbootpatcher/CommandUtils.java, Android_GUI/src/com/github/chenxiaolong/dualbootpatcher/socket/MbtoolConnection.java
Android N's toybox has bad argument parsing code and cannot handle:
mount -o remount,rw /
which prevents us from putting mbtool in rootfs.
=> Android GUI: Launch mbtool from a tmpfs if possible

Android_GUI/res/layout/fragment_patcher.xml, Android_GUI/res/values/strings.xml, Android_GUI/src/com/github/chenxiaolong/dualbootpatcher/patcher/PatchFileFragment.java, Android_GUI/src/com/github/chenxiaolong/dualbootpatcher/patcher/PatcherUtils.java
This allows zipped Odin tarballs to be patched since it won't be
ambiguous as to whether MultiBootPatcher or OdinPatcher should be used.
=> Android GUI: Add option for explicitly patching Odin images

data/devices/motorola.yml
Chen, can you merge this and create an apk so that I can test this. I am not able to build the apk locally. Lots of errors starting with minimum cmake version needed being 3.6.0, I am running peppermint OS which comes with cmake 3.5.1. Even after manually fixing it by upgrading cmake, i get errors 
`CMake Error at cmake/android.toolchain.cmake:47 (file):
file failed to open for reading (No such file or directory):
/home/sileshn/DualBootPatcher/source.properties
Call Stack (most recent call first):
/usr/share/cmake-3.7/Modules/CMakeDetermineSystem.cmake:88 (include)
CMakeLists.txt:3 (project)
CMake Error at cmake/android.toolchain.cmake:51 (message):
Failed to parse Android NDK revision:
/home/sileshn/DualBootPatcher/source.properties.
Call Stack (most recent call first): …
=> Add Moto G4 & G4 plus support

data/devices/yu.yml
Having issues with NDK just like @out386 
```
x86_64-linux-android-g++: error: x86_64-none-linux-android: No such file or
directory
x86_64-linux-android-g++: error: x86_64-none-linux-android: No such file or
directory
x86_64-linux-android-g++: error: unrecognized command line option '-target'
x86_64-linux-android-g++: error: unrecognized command line option '-target'
x86_64-linux-android-g++: error: unrecognized command line option
'-fno-limit-debug-info'
make[4]: *** [CMakeFiles/cmTC_4c8ab.dir/testCXXCompiler.cxx.o] Error 1
make[4]: Leaving directory
`/root/harsh/DualBootPatcher/build/android/android-system_x86_64-prefix/src/android-system_x86_64-build/CMakeFiles/CMakeTmp'
make[3]: *** [cmTC_4c8ab/fast] Error 2
make[3]: Leaving directory …
```
=> Add support for YU Yunique

libmbutil/include/mbutil/mount.h, libmbutil/src/mount.cpp, mbtool/installer.cpp, mbtool/mount_fstab.cpp
This makes mbtool behave more like fs_mgr in Android. If /system,
/cache, or /data already exists and is a symlink, then the symlink is
unlinked and a directory is created in its place.
=> mbtool: Fix mounting ROM directories if target exists and is a symlink

mbtool/installer.cpp
This reverts commit fa4dcd870847a393e66aaa8d84af99a83302ada8.
=> Revert "mbtool: Mount /cache and /data by default to match recovery's behavior"

Android_GUI/src/com/github/chenxiaolong/dualbootpatcher/FileUtils.java, Android_GUI/src/com/github/chenxiaolong/dualbootpatcher/freespace/FreeSpaceFragment.java, Android_GUI/src/com/github/chenxiaolong/dualbootpatcher/nativelib/LibC.java
KitKat's bionic libc has the getmntent() function, but it's just a stub
that doesn't do anything. This commit replaces the getmntent() calls
with equivalent Java code (that actually decodes the fields properly).
=> Android GUI: Get mount points from Java instead of getmntent()

docs/BUILD-App-Android.md
Fix environment variable by also adding ANDROID_NDK. 
Both ANDROID_NDK & ANDROID_NDK_HOME environment variables are used.
=> Fix environment variable, add ANDROID_NDK

Android_GUI/src/com/github/chenxiaolong/dualbootpatcher/nativelib/LibMbp.java, bootimgtool/bootimgtool.cpp, libmbp/include/mbp/bootimage-common.h, libmbp/include/mbp/bootimage.h, libmbp/include/mbp/bootimage/intermediate.h, libmbp/include/mbp/cwrapper/cbootimage.h, libmbp/src/bootimage.cpp, libmbp/src/bootimage/sonyelfformat.cpp, libmbp/src/cwrapper/cbootimage.cpp
The SIN ELF section contains the RSA signature of the boot image, which
is impossible for us to recreate. Thus, readding an existing SIN section
to a modified boot image may result in a broken image. We'll avoid that
by simply ignoring this section.
=> libmbp: Drop support for SIN! image and header in Sony ELF images

data/devices/lenovo.yml
- name: Lenovo K4 Note
id: A7010a48
codenames:
- A7010a48
- K4
- K4 Note
- Lenovo K4 Note
- Vibe X3 Lite
- Lenovo A7010a48
lenovo.yml provided by dg28gadhavi@xda
Build was successful.
=> Add support - Lenovo K4 Note

libmbp/src/patchers/multibootpatcher.cpp, libmbp/src/patchers/odinpatcher.cpp, mbtool/CMakeLists.txt, mbtool/archive_util.cpp, mbtool/archive_util.h, mbtool/backup.cpp, mbtool/bootimg_util.cpp, mbtool/bootimg_util.h, mbtool/installer.cpp, mbtool/installer.h, mbtool/installer_util.cpp, mbtool/installer_util.h, mbtool/ramdisk_patcher.cpp, mbtool/ramdisk_patcher.h, mbtool/rom_installer.cpp
Boot images will no longer be patched by libmbp. Instead, the required
binaries will be added to the zip and mbtool will handle the patching of
the ramdisk. This allows us to guarantee that the ramdisk will be
patched correctly, regardless of how it's stored in the original zip
file.
The only remaining code that uses mbp::BootImage and mbp::CpioFile is
the ramdisk update feature. That will be ported to libmbbootimg in
another commit.
=> mbtool: Switch to libmbbootimg and patch boot image at flash time

data/devices/motorola.yml
My Moto E identifies itself as surnia in the recovery, which makes the
check fail, as surnia is not on the list.  This commit should fix that.
=> Add Support for some Moto E's

data/devices/oneplus.yml
Some ROMs use "oneplus3t" as the codename instead of "OnePlus3T", so when you try to switch ROMs it will say "Could not determine the boot partition because this device's codename 'oneplus3t' is not recognized"
=> Fix OnePlus 3T support

data/devices/samsung/06_galaxy_note_tablet.yml
Hello.
Please add support for Samsung Galaxy Note Pro 12.2 LTE/Wifi.
I compiled the Dual Boot Patcher (debug) with my changes and checked for Samsung Galaxy Note Pro 12.2 LTE - works great, thank you.
=> data: Add support for Samsung Galaxy Note Pro 12.2 LTE/Wifi

mbtool/CMakeLists.txt
=> mbtool: Disable compiler warnings for some external code

cmake/CompilerFlags.cmake
DT_RUNPATH is not transitive, which causes issues with the hosttools
builds. signtool links against libmbsign.so, which can be found via the
$ORIGIN/../lib RPATH. However, libmbsign.so links against libmblog.so
and this second dependency level does not respect DT_RUNPATH.
This commit forces the build to always use RPATH.
For more information:
* https://sourceware.org/bugzilla/show_bug.cgi?id=13945
* https://www.blaenkdenum.com/notes/cmake/
=> cmake: Ensure that DT_RPATH is used instead of DT_RUNPATH (fixes #546)

data/devices/motorola.yml
My mistake
lrwxrwxrwx 1 root root 21 1970-01-19 14:51 userdata -> /dev/block/mmcblk0p54
/dev/block/bootdevice/by-name/userdata /data f2fs rw,seclabel,nosuid,nodev,noatime...
=> motorola: Fix moto z play data partition

data/devices/xiaomi.yml
some user kenzo can't find the partition used, so we add where the exact location
=> update for Xiaomi kenzo and Xiaomi mido

.gitignore, thirdparty/CMakeLists.txt, utilities/CMakeLists.txt, utilities/create.sh.in
AROMA was the only file remaining that was downloaded to `CMAKE_BINARY_DIR`. This commit fixes the CMake files so that it is downloaded to the prebuilts directory.
=> utilities: Don't download AROMA to build directory

thirdparty/CMakeLists.txt
=> thirdparty: Fix URLs to point to dbp.noobdev.io instead of snapshots.noobdev.io

bootimgtool/CMakeLists.txt, bootimgtool/bootimgtool.manifest, bootimgtool/bootimgtool.rc, gui/main.manifest, gui/main.rc
DualBootPatcher never needs to run as admin, but because "patch" is in
the filename, Windows assumes that admin privileges are needed. This
commit adds manifests to all .exe's that are built to indicate that
they should run with the invoking user's privileges.
=> gui,bootimgtool: Add manifests to .exe's to prevent unnecessary UAC prompts

data/devices/huawei.yml
correcting boot-dev block path for huawei Y635
=> Add additional block device paths for Huawei Y635

libmbcommon/include/mbcommon/file/callbacks_p.h, libmbcommon/include/mbcommon/file/fd_p.h, libmbcommon/include/mbcommon/file/memory_p.h, libmbcommon/include/mbcommon/file/posix_p.h, libmbcommon/include/mbcommon/file/win32_p.h, libmbcommon/include/mbcommon/file_p.h, libmbcommon/src/file.cpp
=> libmbcommon: Disable copy constructor and assignment operator for pimpl classes

data/devices/huawei.yml
The codename was mistyped(HWVNS-N) instead of HWVNS-H(correct codename) and also included other official codename: venus
=> Codename update for p9 lite

cmake/android.toolchain.cmake
Set CMAKE_SYSROOT_COMPILE in Android toolchain file (android-ndk/ndk#467)
=> Add support for CMake 3.9

docs/DOCKER.md
docker doc should updated, i was trying to build and faced error can't find image chenxiaolong/dualbootpatcher:9.2.0-1-android
so it should be chenxiaolong/dualbootpatcher:9.2.0-2-android
=> Update docs: docker is release 2

Android_GUI/build.gradle.in, android/CMakeLists.txt, libmbcommon/include/mbcommon/common.h
This was an oversight when DualBootPatcher switched from having just
libmbp.so to having several different libraries. When linked against
static libstdc++, symbols that were meant to be globally unique got
duplicated in each library.
This was particularly problematic for the
_ZNSs4_Rep20_S_empty_rep_storageE symbol. It's a statically allocated
buffer used as the representation for empty strings. If an empty
std::string is passed from one library to another and the second
library performs an action that causes a reallocation, then the second
library will free() the _S_empty_rep_storage buffer and crash. The
normal `this != &_S_empty_rep()` guard doesn't work because each
library has its own _S_empty_rep_storage.
=> android: Use shared libstdc++ for android-app target

data/devices/htc.yml
=> Add extra codename for HTC One M8

libmbcommon/CMakeLists.txt, libmbsparse/tests/test_sparse.cpp
=> libmbcommon,libmbsparse: Fix zero-length format string warnings

libmbcommon/src/file/fd.cpp, libmbcommon/src/file/posix.cpp, libmbcommon/src/file/win32.cpp
=> libmbcommon: Cast enum class to integer before passing to printf

libmbutil/src/selinux.cpp
=> libmbutil: selinux.cpp: Use mb::format() instead of asprintf()

data/devices/walton.yml
The Device Name "**Primo RX5**" was not complete and not easily find-able from the Download section.
I forgot to add the Vendor name "**Walton**" in the starting.
So, now I used the Complete Device Name as "**Walton Primo RX5**" which also includes Company name.
=> Update Device Name for "Primo RX5"

data/devices/motorola.yml
Add Moto X Pro support.
This is a old device, the hardware almost like nexus 6, released in 2015, china retail version.
=> devices: Add Motorola Moto X Pro (shamu_t)

data/devices/lenovo.yml
Add A6020l36 to Lenovo Vibe K5 codenames
=> Add A6020l36 to Lenovo Vibe K5 codenames

libmbcommon/include/mbcommon/file_error.h, libmbcommon/src/file/fd.cpp, libmbcommon/src/file/memory.cpp, libmbcommon/src/file/posix.cpp, libmbcommon/src/file/win32.cpp, libmbcommon/src/file_error.cpp, libmbcommon/tests/file/mock_test_file.cpp, libmbcommon/tests/file/test_fd.cpp, libmbcommon/tests/file/test_posix.cpp, libmbcommon/tests/file/test_win32.cpp, libmbcommon/tests/test_file_error.cpp, libmbsparse/src/sparse.cpp
=> libmbcommon: file: Use asserts for invalid arguments instead of runtime errors

libmbcommon/include/mbcommon/common.h
=> libmbcommon: Fix compiler warning when MB_UNREACHABLE is passed only one argument

examples/bingrep.cpp, examples/desparse.cpp, libmbbootimg/src/reader.cpp, libmbbootimg/src/writer.cpp, libmbcommon/include/mbcommon/file/open_mode.h, libmbcommon/src/file.cpp, libmbcommon/src/file/fd.cpp, libmbcommon/src/file/open_mode.cpp, libmbcommon/src/file/posix.cpp, libmbcommon/src/file/win32.cpp, libmbcommon/tests/file/test_fd.cpp, libmbcommon/tests/file/test_posix.cpp, libmbcommon/tests/file/test_win32.cpp, libmbpatcher/src/patchers/odinpatcher.cpp, libmbpatcher/src/private/fileutils.cpp, libmbpatcher/src/private/miniziputils.cpp, mbtool/installer_util.cpp, odinupdater/fuse-sparse.cpp, odinupdater/odinupdater.cpp
=> libmbcommon: Fix naming of FileOpenMode variants

libmbcommon/include/mbcommon/file.h, libmbcommon/src/file.cpp, libmbcommon/src/file/posix.cpp, libmbcommon/src/file/win32.cpp, libmbcommon/src/file_util.cpp, libmbsparse/src/sparse.cpp, libmbsparse/tests/test_sparse.cpp
There's no need to ever revert from the FATAL state to the OPENED state.
=> libmbcommon: file: Remove ability to clear fatal status

libmbbootimg/include/mbbootimg/format/loki_error.h, libmbbootimg/include/mbbootimg/format/segment_error_p.h, libmbbootimg/include/mbbootimg/format/sony_elf_error.h, libmbbootimg/src/format/android_reader.cpp, libmbbootimg/src/format/android_writer.cpp, libmbbootimg/src/format/loki.cpp, libmbbootimg/src/format/loki_error.cpp, libmbbootimg/src/format/loki_reader.cpp, libmbbootimg/src/format/loki_writer.cpp, libmbbootimg/src/format/mtk_reader.cpp, libmbbootimg/src/format/mtk_writer.cpp, libmbbootimg/src/format/segment_error.cpp, libmbbootimg/src/format/segment_reader.cpp, libmbbootimg/src/format/segment_writer.cpp, libmbbootimg/src/format/sony_elf_error.cpp, libmbbootimg/src/format/sony_elf_reader.cpp, libmbbootimg/src/format/sony_elf_writer.cpp, libmbbootimg/tests/format/test_loki_reader.cpp, libmbcommon/include/mbcommon/file_error.h, libmbcommon/include/mbcommon/file_util.h, libmbcommon/src/file_error.cpp, libmbcommon/src/file_util.cpp, libmbcommon/tests/test_file_util.cpp, libmbsparse/include/mbsparse/sparse_error.h, libmbsparse/src/sparse.cpp, libmbsparse/src/sparse_error.cpp, libmbsparse/tests/test_sparse.cpp, mbtool/installer_util.cpp
=> libmbcommon: Replace file_*_fully() with file_*_retry() and file_*_exact()

libmbpatcher/include/mbpatcher/patchers/odinpatcher.h, libmbpatcher/include/mbpatcher/patchers/zippatcher.h
=> libmbpatcher: Fix warning about forward declaration not matching real declaration

data/devices/oneplus.yml
This is to prevent errors that TrustZone could not be verified.
=> Add TrustZone block device to OnePlus 3T

Android_GUI/CMakeLists.txt
This changed when the Android gradle plugin was updated to 3.0.
=> Android GUI: Fix APK path when using the apk-install CMake target

data/devices/samsung/00_galaxy_s.yml
Some custom roms change the code name to Zeroltexxx which makes the app unusable on these roms
=> Update Galaxy S6 Edge Codenames

data/devices/lenovo.yml
New ROMs now use the passion assert.
=> devices: lenovo: Add  new codename for P1a41

thirdparty/CMakeLists.txt
This is something I overlooked in a7f83d6e76c0cd409fbfd99cd3fe8a9372e7633d. When a dependency is updated, CMake won't rerun the library and include path searches, even though CMAKE_FIND_ROOT_PATH is changed. Thus, we have to go back to hard coding paths to ensure they are updated.
=> thirdparty: Explicitly set paths to prebuilt libraries

Android_GUI/src/com/github/chenxiaolong/dualbootpatcher/switcher/RomDetailActivity.kt
This can happen if ro.build.version.release or ro.build.display.id are
not set in /system/build.prop for a ROM.
=> Android GUI: Fix crash if daemon returns ROM information with incomplete data

libmbpatcher/CMakeLists.txt, libmbpatcher/include/mbpatcher/autopatchers/magiskpatcher.h, libmbpatcher/src/autopatchers/magiskpatcher.cpp, libmbpatcher/src/autopatchers/standardpatcher.cpp, libmbpatcher/src/patcherconfig.cpp, libmbpatcher/src/patchers/zippatcher.cpp
This will hopefully be a temporary workaround until we support hooking
the mount/umount system calls with ptrace.
=> libmbpatcher: Add initial support for magisk installer

libmbutil/include/mbutil/hash.h, libmbutil/src/hash.cpp, mbtool/installer.cpp, mbtool/installer.h, mbtool/installer_util.cpp, mbtool/ramdisk_patcher.cpp, mbtool/ramdisk_patcher.h, mbtool/switcher.cpp
This commit updates the installer so that the /init -> /mbtool symlink
is removed and /init.orig is moved back to /init prior to flashing. This
ensures that flashing packages that touch /init won't adversely affect
multibooting. Magisk is an example of such a package.
=> mbtool: installer: Undo /init symlink patch before flashing

data/devices/xiaomi/03_redmi.yml
It seems better to add a manufacturer name ‘Xiaomi’.
By the way,thanks for your effort.
=>  Change device name from 'Redmi 5' Plus to 'Xiaomi Redmi 5 Plus'.

data/devices/oneplus.yml
Most used codename for OnePlus 5T is "dumpling", so is recommended to be added due to TWRP restrictions, if not, dual patched zips are not supported to be directly flashed.
=> OnePlus 5T codenames revision

libmbpatcher/include/mbpatcher/patchers/zippatcher.h, libmbpatcher/src/patchers/odinpatcher.cpp, libmbpatcher/src/patchers/ramdiskupdater.cpp, libmbpatcher/src/patchers/zippatcher.cpp, mbtool/installer.cpp, mbtool/installer.h
This commit updates mbtool to always patch the boot image after an installation. Previously, it would compute the SHA512 checksum of the boot partition before and after flashing and only patch the boot image if they differed. This was fine until mbtool was updated to partially undo certain patches before installation (1c0a9079481921f95e74308f66d2329804949bbc). When flashing a zip that did not touch the boot partition, the partially unpatched boot image would remain, rendering the system unbootable.
The original behavior was introduced in commit a5a2c83128b97b6778a825020a00c85a89fdbd6f. At the time, it was unsafe to assume that the current boot partition contents belonged to the target ROM ID. However, this is no longer the case, since `/sdcard/MultiBoot/[ROM ID]/boot.img` is flashed to …
=> mbtool: installer: Always patch boot image

libmbsparse/src/sparse.cpp, libmbsparse/tests/test_sparse.cpp
This prevented files with oversized sparse headers from being read
properly, which broke the flashing of patched Samsung Odin images.
=> libmbsparse: Fix incorrect file offset when skipping bytes in unseekable source file

data/devices/meizu.yml
Add new codename
Add missing 6.0+ kernel partition mounts
Remove useless flag from boot ui
Decrease default brightness in boot ui
=> data: Meizu M2 update

mbtool/daemon_v3.cpp, mbtool/installer.cpp, mbtool/installer.h, mbtool/romconfig.cpp, mbtool/romconfig.h
This allows showing the build and version numbers on the ROMs page of
the Android app for ROMs that don't get mounted by default.
(Fixes #1013)
=> mbtool: Cache version and build properties during installation

mbtool/sepolpatch.cpp
AOSP now labels apps with different types depending on their target API
version. untrustd_app_25 is used to label any app targeting API 25 or
lower (including the DualBootPatcher app).
https://android.googlesource.com/platform/system/sepolicy/+/bacb6d79360f3591680b215177602dcdc3181bf3
(Fixes #1020)
=> mbtool: sepolpatch.cpp: Allow untrusted_app_25-labeled processes to talk to mb_exec-labeled sockets

data/devices/samsung/02_galaxy_a_j.yml
Support for ALL J5 Pro (2017) Variants.
Edits
Support for A8/A8+ 2018
=> Add Samsung Galaxy J5 2017 (Exynos)//Samsung Galaxy A8/A8+ 2018 (Exynos)

data/devices/leeco.yml
x2: TWRP now uses arm64-v8a
zl0: added Le Pro3 Elite
=> leeco: fix x2 and add zl0

data/devices/samsung/01_galaxy_note.yml
All the information regarding partitions are exactly the same as the previously added model(N910C)
=> devices: samsung: Add support for SM-N916K

libmbutil/include/mbutil/mount.h, libmbutil/src/mount.cpp
=> libmbutil: Remove unneeded MountError::EndOfFile error code

mbtool/sepolpatch.cpp
=> mbtool: Allow system_server to use fds from mbtool (fixes framework reboot on TW Oreo)

libmbutil/include/mbutil/archive.h, libmbutil/src/archive.cpp, mbtool/backup.cpp, mbtool/rom_installer.cpp, mbtool/update_binary.cpp
The backup tarballs are split at exactly 4 GiB by default. There is
nothing special about the file format. Concatenating all the split
components produces the complete tarball.
Fixes: #1103
=> Add support for split archive backups

libmbutil/src/path.cpp, libmbutil/src/selinux.cpp, libmbutil/src/vibrate.cpp, mbtool/appsync.cpp, mbtool/daemon.cpp, mbtool/mount_fstab.cpp, odinupdater/odinupdater.cpp
std::this_thread::sleep_for() is more versatile and properly handles
EINTR (at least with libstdc++).
=> Use std::this_thread::sleep_for() instead of C/POSIX sleep functions

libmbutil/src/reboot.cpp
=> libmbutil: remount_ro_done(): Fix incorrect check causing 1 minute delay during emergency reboot

mbtool/daemon_v3.cpp
=> mbtool: daemon_v3.cpp: Fix sign conversion warning for mode_t variable

mbtool/init.cpp
Otherwise, mbtool crashes badly on exit because the UeventThread
destructor logs and the global logging mutex has already been destroyed.
=> mbtool: init.cpp: Create UeventThread as local variable

examples/libmbpatcher_test.cpp, libmbutil/include/mbutil/file.h, libmbutil/src/cmdline.cpp, libmbutil/src/file.cpp, mbbootui/main.cpp, mbtool/emergency.cpp, mbtool/init.cpp, mbtool/installer.cpp, mbtool/switcher.cpp, mbtool/utilities.cpp
There are more/better helper functions for std::string and there's no
reason not to use it now that std::string::data() returns a mutable
pointer in C++17.
=> libmbutil: Change file_read_all() to return std::string

mbtool/daemon.cpp
Creating a new mount namespace in the main/listening process of the
mbtool daemon causes apps to not be able to access the internal storage
on TouchWiz Oreo ROMs (at least in the G955FXXU1CRD7 firmware).
This change shouldn't affect anything since the main process didn't
mount anything anyway. The child processes spawned when a connections
are made will still unshare their mount namespaces.
Fixes: #1167
=> mbtool: daemon: Don't unshare mount namespace in listening process

thirdparty/valgrind/.gitignore, thirdparty/valgrind/PKGBUILD
Binaries in /data cannot exec() other processes as root on TouchWiz
ROMs.
=> thirdparty: Install valgrind to /cache/valgrind instead of /data/local/Inst

mbtool/include/util/property_service.h, mbtool/init.cpp, mbtool/installer.cpp, mbtool/mount_fstab.cpp, mbtool/multiboot.h, mbtool/properties.cpp, mbtool/ramdisk_patcher.cpp, mbtool/ramdisk_patcher.h, mbtool/roms.cpp
Some devices have `/default.prop` symlinked to some other file that's not in the ramdisk, which prevents properties from being written to it during installation. The properties don't really have to live in that file though. This PR updates mbtool to write the properties to `/dbp.prop` and ensures that it gets loaded during boot. For mbtool's pre-boot phase, the file is explicitly loaded to the property service. For the Android init phase, a oneshot service is added to load the file.
Fixes: #1191
=> Store DualBootPatcher properties in /dbp.prop instead of /default.prop

libmbutil/src/file.cpp, mbtool/init.cpp
`mb::util::file_read_all()` previously seeked to the end of the file to get the file size and this fails when reading `/proc/cmdline`.
=> Fix parsing of /proc/cmdline

mbtool/installer_util.cpp
=> mbtool: installer_util.cpp: Choose a temp dir that always exists

mbtool/installer.cpp
This should fix the flashing of packages that use an updater binary
compiled against bionic 8.0+.
=> mbtool: Don't use legacy properties unless they're supported

Android_GUI/src/com/github/chenxiaolong/dualbootpatcher/socket/MbtoolUtils.kt, mbtool/installer.cpp, mbtool/installer_util.cpp, mbtool/installer_util.h
Prior to flashing the zip, mbtool will flash the kernel for the target ROM and undo some ramdisk patches (specifically the `/init` symlink patch). However, `InstallerUtil::patch_boot_image()` was being invoked with the same path for the input and output files, leading to corruption of boot image entries that were directly copied. This included any entry that was not the kernel or ramdisk.
The device tree entry was most commonly corrupted and would manifest via boot loops or other hardware initialization failures, such as a modem boot failure on the Galaxy S8+.
This issue only affected zips that modify the existing boot image, like Magisk or Anykernel-based zips. ROMs that overwrote the boot partition were not affected.
A warning message will be posted at https://dbp.noobdev.io/downloads/ …
=> mbtool: Fix boot image corruption caused by reading and writing to the same file

docker/common.sh, docker/template/Dockerfile.base.in, docs/build/Docker.md
The Fedora package is currently broken due to:
https://bugzilla.redhat.com/show_bug.cgi?id=1653103
=> docker: Install transifex-client in a virtualenv

libmbbootimg/src/reader.cpp
=> libmbbootimg: reader.cpp: Fix Clang warning about value copy

docker/common.sh, docker/template/Dockerfile.base.in, docs/build/Docker.md
The upstream bug with the RPM packaging has been fixed.
https://bugzilla.redhat.com/show_bug.cgi?id=1653103
This reverts commit 8dea723f1e028833587f23d20750b30b0573fa83.
=> Revert "docker: Install transifex-client in a virtualenv"

libmbbootimg/src/format/loki.cpp, libmbbootimg/src/format/loki_reader.cpp, libmbbootimg/src/format/mtk_reader.cpp, libmbbootimg/src/format/segment_reader.cpp, libmbbootimg/src/format/sony_elf_reader.cpp, libmbbootimg/tests/format/test_loki_reader.cpp, libmbcommon/include/mbcommon/file.h, libmbcommon/src/file/fd.cpp, libmbcommon/src/file/memory.cpp, libmbcommon/src/file/posix.cpp, libmbcommon/src/file/win32.cpp, libmbcommon/src/file_util.cpp, libmbcommon/tests/file/test_fd.cpp, libmbcommon/tests/file/test_memory.cpp, libmbcommon/tests/file/test_posix.cpp, libmbcommon/tests/file/test_win32.cpp, libmbcommon/tests/test_file_util.cpp, libmbsparse/src/sparse.cpp, libmbsparse/tests/test_sparse.cpp, odinupdater/odinupdater.cpp
=> libmbcommon: Remove unneeded includes from file.h

libmbutil/CMakeLists.txt, libmbutil/tests/main.cpp, libmbutil/tests/test_archive.cpp, mbtool/src/main.cpp
Android's bionic libc now respects setlocale(), so mbtool's previous `setlocale(LC_ALL, "C")` call prevented UTF-8 encodings from working when creating or extracting backups. The locale argument has been changed to `""` so that the encoding specified by the standard environment variables is used instead. If the environment variables are unset, bionic defaults to `UTF-8`.
This PR also adds a test to ensure that this doesn't break in the future.
Fixes #1265
=> mbtool: Fix setlocale call now that bionic libc has basic locale support

libmbutil/src/properties.cpp, mbtool/src/recovery/installer.cpp
This caused property_iter() to return the opposite status and property_get_all() to return std::nullopt when successful. This broke the setting of legacy properties when flashing from recovery.
=>  libmbutil: Fix incorrect return value checking of __system_property_foreach

Android_GUI/src/main/java/com/github/chenxiaolong/dualbootpatcher/AboutFragment.kt, Android_GUI/src/main/java/com/github/chenxiaolong/dualbootpatcher/MainActivity.kt, Android_GUI/src/main/java/com/github/chenxiaolong/dualbootpatcher/appsharing/AppListFragment.kt, Android_GUI/src/main/java/com/github/chenxiaolong/dualbootpatcher/appsharing/AppSharingSettingsFragment.kt, Android_GUI/src/main/java/com/github/chenxiaolong/dualbootpatcher/patcher/InstallLocation.kt, Android_GUI/src/main/java/com/github/chenxiaolong/dualbootpatcher/patcher/PatchFileFragment.kt, Android_GUI/src/main/java/com/github/chenxiaolong/dualbootpatcher/patcher/PatcherOptionsDialog.kt, Android_GUI/src/main/java/com/github/chenxiaolong/dualbootpatcher/pathchooser/PathChooserActivity.kt, Android_GUI/src/main/java/com/github/chenxiaolong/dualbootpatcher/pathchooser/PathChooserDialog.kt, Android_GUI/src/main/java/com/github/chenxiaolong/dualbootpatcher/picasso/PaletteGeneratorTransformation.kt, Android_GUI/src/main/java/com/github/chenxiaolong/dualbootpatcher/socket/MbtoolErrorActivity.kt, Android_GUI/src/main/java/com/github/chenxiaolong/dualbootpatcher/switcher/AutomatedSwitcherActivity.kt, Android_GUI/src/main/java/com/github/chenxiaolong/dualbootpatcher/switcher/InAppFlashingFragment.kt, Android_GUI/src/main/java/com/github/chenxiaolong/dualbootpatcher/switcher/MbtoolTaskOutputFragment.kt, Android_GUI/src/main/java/com/github/chenxiaolong/dualbootpatcher/switcher/RomDetailActivity.kt, Android_GUI/src/main/java/com/github/chenxiaolong/dualbootpatcher/switcher/SwitcherListFragment.kt
=> Android GUI: Use java.lang.Class.getName() instead of getCanonicalName()

mbtool/include/util/sepolpatch.h, mbtool/src/util/sepolpatch.cpp
On policy versions < 29, the type_names field of the constraint
expression is empty, so adding the /data/media type to the
mlstrustedobject attribute would have no effect. There's no way to tell
that a constraint applies to a particular attribute. This would prevent
apps from writing to /data/media on devices where it is labeled with a
type that doesn't exist in the policy (and thus, mbtool has to create
it).
This commit adds the ability to add the dynamically created type to
every constraint that applies to the expected /data/media type.
Fixes: #1396
=> mbtool: sepolpatch.cpp: Fix MLS constraint handling for /data/media type
